name: lyrics_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  json_serializable: ^6.6.1
  simple_circular_progress_bar: ^1.0.2
  rounded_tabbar_widget: ^0.0.2
  flutter_spinkit: ^5.2.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.16
  flutter_lints: ^2.0.0
  cloud_firestore: ^4.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:       
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpg"

flutter_native_splash:
  color: '#FFD000'
  image: 'assets/images/app_icon.jpg'
  color_dark: '#FFD000'
  image_dark: 'assets/images/app_icon.jpg'
  fullscreen: true
  android_12:
    icon_background_color: '#FFD000'
    image: 'assets/images/app_icon.jpg'
    icon_background_color_dark: '#FFD000'
    image_dark: 'assets/images/app_icon.jpg'

flutter:
  uses-material-design: true
